### ISSUE TITLE
Update for 1.13 <3333

### ISSUE THREAD

**Issue by CloudeLecaw** [blablubbabc/HomeStations#3]
Hello blablubbabc

Is it possible to upgrade the Homestation Plugin for 1.13?

Currently the Plugin  does not work in 1.13 - means it does not recognice the stations anymore (may because of the removing of BlockIDs)

**Comment by blablubbabc** [comment]
I just tested v1.8 on the lastest Spigot 1.13-pre7 build, and encountered no issues. Can you test again and provide some details on what you might be doing differently than me?

**Comment by CloudeLecaw** [comment]
now i tested it aggain the command and button setup work now. but if i press it i get bursted in the air, the screen is have freezing and then i stand at the same station 🥉 

Edit: Now after setting them aggain it seem to work :§
im confussed a bit about that fact now that its working

**Comment by blablubbabc** [comment]
¯\\_(ツ)_/¯

**Comment by CloudeLecaw** [comment]
Just one Question is remaining..
the big firework,,,,
may u also saw that the firework seems to be "endless Long and can lag the Server? :3


...with the Default cofnig.,.
```
Firework Effect 1:
  Colors:
  - 255;165;0
  Fade Colors:
  - 255;0;0
  Flicker: false
  Trail: true
Firework Effect 2:
  Colors:
  - 255;255;0
  Fade Colors: []
  Flicker: false
  Trail: false
Upward:
  Teleport:
    Y Velocity: 2.0
    Delay in Ticks: 15
  Effect:
    Maximum Range: 80.0
    Distance between Fireworks: 2.5
Downward:
  Effect:
    Offset: 3.0
  Teleport:
    Y Offset: 3.0
Teleport Costs: 0.0
```
![image](https://user-images.githubusercontent.com/12080017/42949085-452d75cc-8b71-11e8-93ab-2811b7e05505.png)


i modificated the config a bit, this make it not so laggy but still Shows a firework _(i thoughti t should be off if all is false..hmm)
```
Firework Effect 1:
  Colors:
  - 255;165;0
  Fade Colors: []
  Flicker: false
  Trail: false
Firework Effect 2:
  Colors:
  - 255;255;0
  Fade Colors: []
  Flicker: false
  Trail: false
Upward:
  Teleport:
    Y Velocity: 1.0
    Delay in Ticks: 15
  Effect:
    Maximum Range: 3.0
    Distance between Fireworks: 10.5
Downward:
  Effect:
    Offset: 3.0
  Teleport:
    Y Offset: 3.0
Teleport Costs: 0.0
```
![image](https://user-images.githubusercontent.com/12080017/42949527-392c21be-8b72-11e8-8d33-619708105d41.png)

this is a nice workarround to fix the laganimation but it is not the solution of the Problem itself ..;)

**Comment by blablubbabc** [comment]
I think I already limited it quite a bit in the past (from 255 to 80). But sure, if that still causes issues on your server, then go ahead and change it to your liking. The main idea behind the row of fireworks going into the sky was however for it to be visible by nearby players.

Regarding lag: Were you really able to trackdown server lag to those firework effects? I would expect this to either be primarily client lag, due to the large amount of particles / sounds, or (since I already limited the fireworks in the past) it could even be that there is no lag at all and you only think there is do to irregular differences in the arrival times of the firework effects at the client due to unstable network lag (which is nothing I can prevent and may vary from connection to connection). Have you tried it on a local server yet?

Edit: I did some more testing, and yes there seems to be client lag. However, even with your settings, if the station which I get teleported to is far away, I get client lag as well (due to chunk updates, due to the teleport).
